name: angular_fire
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
author: Pablo Cariel <pablocariel@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0-alpha
  firebase: ^4.0.0

dev_dependencies:
  angular_test: ^1.0.0-beta+4
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points: 
      - 'example/main.dart'
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dart2js